# NumPy Indexing and Selection

In this lecture we will discuss how to select elements or groups of elements from an array.

In [1]:
import numpy as np

In [2]:
#Creating sample array
arr = np.arange(0,11)

In [3]:
#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [4]:
#Get a value at an index
arr[8]

np.int64(8)

In [5]:
#Get values in a range
arr[0:5]

array([0, 1, 2, 3, 4])

In [6]:
#Get values in a range
arr[1:] # same as arr[1:end]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
arr[:5] # same as arr[0:5]

array([0, 1, 2, 3, 4])

In [8]:
arr[0:5]

array([0, 1, 2, 3, 4])

## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [9]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
#Setting a value with index range (Broadcasting)
arr[0:5]=10

#Show
arr

array([10, 10, 10, 10, 10,  5,  6,  7,  8,  9, 10])

In [11]:
# Reset array, we'll see why I had to reset in  a moment
arr = np.arange(0,11)

#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
#Important notes on Slices
slice_of_arr = arr[0:5]

#Show slice
slice_of_arr

array([0, 1, 2, 3, 4])

In [13]:
#Change Slice
slice_of_arr[:]=99

#Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99])

Now note the changes also occur in our original array.

In [14]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

Data is not copied, it's a view of the original array. This avoids memory problems.

In [15]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
#To get a copy, need to be explicit

arr_copy = arr.copy()

arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
arr_copy[0:5] = 99
arr_copy

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [18]:
# the original array is unchanged
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

In [19]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [20]:
#Indexing row
arr_2d[0]


array([ 5, 10, 15])

In [21]:
arr_2d[0:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [22]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

np.int64(20)

In [23]:
# Getting individual element value
arr_2d[1,0]

np.int64(20)

In [24]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [25]:
# 2D array slicing

#Shape (2,2) from top left corner
arr_2d[:2,:2]

array([[ 5, 10],
       [20, 25]])

In [26]:
# top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [27]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [28]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

In [29]:
arr_2d[:,0] # first column

array([ 5, 20, 35])

In [30]:
arr_2d[:,0].shape

(3,)

In [31]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [32]:
arr_2d[:,:2] # first 2 columns

array([[ 5, 10],
       [20, 25],
       [35, 40]])

In [33]:
arr_2d[1:,:] # last 2 rows

array([[20, 25, 30],
       [35, 40, 45]])

In [34]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [35]:
arr_2d[:,0].shape # 1-d array

(3,)

In [36]:
arr_2d[:,0]

array([ 5, 20, 35])

In [37]:
arr_2d[:,0].reshape(3,1) #  convert it into 2-d array of same dimension 

array([[ 5],
       [20],
       [35]])

In [38]:
arr_2d[:,0].reshape(3,1).shape 

(3, 1)

### Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order, to show this, let's quickly build out a numpy array:

In [39]:
#Set up matrix
arr2d = np.zeros((10,5))

arr2d

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [40]:
arr2d.shape

(10, 5)

In [41]:
# # rows of array
num_row = arr2d.shape[0]
print(num_row)

10


In [42]:
num_col = arr2d.shape[1]
print(num_col)

5


In [43]:
#Set up array

for i in range(num_row):
    arr2d[i] = i 
arr2d

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9.]])

Fancy indexing allows the following

In [44]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8.]])

In [45]:
#Allows in any order
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7.]])

## Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [46]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [48]:
bool_arr = arr>4

In [49]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [50]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [51]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
arr[arr<=4]

array([1, 2, 3, 4])

In [54]:
arr[arr==4]

array([4])

In [55]:
arr[(arr>3) & (arr<8)]

array([4, 5, 6, 7])