# NumPy Operations

## Arithmetic

You can easily perform array with array arithmetic, or scalar with array arithmetic. Let's see some examples:

In [1]:
import numpy as np
arr = np.arange(0,10)

In [2]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr + 1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
2*arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
arr + arr # element-wise addition

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
arr * arr # element-wise product or Hadmard product

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [8]:
arr0 = np.arange(1,5)
arr0

array([1, 2, 3, 4])

In [10]:
arr*arr0

ValueError: operands could not be broadcast together with shapes (10,) (4,) 

In [11]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
# Warning on division by zero, but not an error!
# Just replaced with nan
arr/arr # element-wise division

/var/folders/r_/k3h6lwv14rgc3xy2gxtsnjyd1_8f0t/T/ipykernel_43144/352479459.py:3: RuntimeWarning: invalid value encountered in true_divide
  arr/arr # element-wise division


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [11]:
# Also warning, but not an error instead infinity
1/arr

/var/folders/r_/k3h6lwv14rgc3xy2gxtsnjyd1_8f0t/T/ipykernel_38430/1360216608.py:2: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [13]:
arr**2 # element-wise power

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [14]:
arr**0.5

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

## Universal Array Functions

Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

In [15]:
#Taking Square Roots, same as arr**0.5
np.sqrt(arr) # same as arr**0.5

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [15]:
arr**0.5

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [16]:
#Calcualting exponential (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [17]:
np.max(arr) #same as arr.max()

9

In [18]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [19]:
np.log(arr)

/var/folders/r_/k3h6lwv14rgc3xy2gxtsnjyd1_8f0t/T/ipykernel_43144/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

## Multiplications

Matrix multiplications: https://docs.scipy.org/doc/numpy/reference/generated/numpy.matmul.html#numpy.matmul

inner product: https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html



In [21]:
A, B = np.random.randn(5,5), np.random.randn(5,5)

In [22]:
A

array([[ 0.12949819,  0.29960067, -2.72246876,  1.16667571, -0.92899104],
       [-0.42588348, -0.17695556, -1.32709576, -0.08729724, -1.64767293],
       [ 1.23587847, -1.10695289, -0.87671457,  0.94193726,  1.04611343],
       [ 0.42184134, -0.46048284,  1.23285936,  0.49637539, -1.0951898 ],
       [-1.44973529,  0.43738971,  0.17202097, -1.73502474, -1.48754077]])

In [23]:
B

array([[ 0.42653854, -0.9043467 ,  0.00585813, -0.01921319, -1.35575439],
       [ 0.96325833, -0.65679592,  2.37627616,  1.70740775, -0.08271498],
       [ 0.43163891, -1.79870573,  0.14382959,  0.41359682, -1.80801589],
       [-0.62177831,  0.63334601,  1.58612242, -1.00862267, -0.90732253],
       [-0.76445522,  0.7545867 , -0.73533914, -0.34957317, -0.31505523]])

In [24]:
B.transpose() # transpose

array([[ 0.42653854,  0.96325833,  0.43163891, -0.62177831, -0.76445522],
       [-0.9043467 , -0.65679592, -1.79870573,  0.63334601,  0.7545867 ],
       [ 0.00585813,  2.37627616,  0.14382959,  1.58612242, -0.73533914],
       [-0.01921319,  1.70740775,  0.41359682, -1.00862267, -0.34957317],
       [-1.35575439, -0.08271498, -1.80801589, -0.90732253, -0.31505523]])

In [25]:
B.T # transpose

array([[ 0.42653854,  0.96325833,  0.43163891, -0.62177831, -0.76445522],
       [-0.9043467 , -0.65679592, -1.79870573,  0.63334601,  0.7545867 ],
       [ 0.00585813,  2.37627616,  0.14382959,  1.58612242, -0.73533914],
       [-0.01921319,  1.70740775,  0.41359682, -1.00862267, -0.34957317],
       [-1.35575439, -0.08271498, -1.80801589, -0.90732253, -0.31505523]])

In [26]:
A*B # element-wise product

array([[ 0.05523597, -0.27094288, -0.01594859, -0.02241556,  1.25948368],
       [-0.41023581,  0.11622369, -3.15354602, -0.14905198,  0.13628723],
       [ 0.53345323,  1.9910825 , -0.12609749,  0.38958225, -1.89138971],
       [-0.26229179, -0.29164497,  1.95546586, -0.50065547,  0.99369038],
       [ 1.10825772,  0.33004846, -0.12649375,  0.60651809,  0.46865751]])

In [27]:
np.dot(A,B) 

array([[-0.84653623,  4.62093752,  2.85473496, -1.46893721,  3.95604992],
       [ 0.38891591,  1.58982333,  0.45926849, -0.17880308,  3.58975524],
       [-2.30293894,  2.57228652, -2.02450367, -3.59212392, -1.18309662],
       [ 0.79710584, -2.80863704,  0.67820653, -0.40223669, -2.86818102],
       [ 2.09316131, -1.50697702, -0.60250699,  3.11579357,  3.66117421]])

In [29]:
C = np.random.rand(4,4)
C

array([[0.13525112, 0.81079876, 0.93122365, 0.05442034],
       [0.96204268, 0.87640409, 0.01745211, 0.2574315 ],
       [0.46146326, 0.84005564, 0.20354876, 0.0096023 ],
       [0.1859475 , 0.05710757, 0.5380385 , 0.29405169]])

In [30]:
np.dot(A,C)

ValueError: shapes (5,5) and (4,4) not aligned: 5 (dim 1) != 4 (dim 0)

In [33]:
np.matmul(A,B)

array([[-0.84653623,  4.62093752,  2.85473496, -1.46893721,  3.95604992],
       [ 0.38891591,  1.58982333,  0.45926849, -0.17880308,  3.58975524],
       [-2.30293894,  2.57228652, -2.02450367, -3.59212392, -1.18309662],
       [ 0.79710584, -2.80863704,  0.67820653, -0.40223669, -2.86818102],
       [ 2.09316131, -1.50697702, -0.60250699,  3.11579357,  3.66117421]])

In [34]:
np.dot(A,B) 

array([[-0.84653623,  4.62093752,  2.85473496, -1.46893721,  3.95604992],
       [ 0.38891591,  1.58982333,  0.45926849, -0.17880308,  3.58975524],
       [-2.30293894,  2.57228652, -2.02450367, -3.59212392, -1.18309662],
       [ 0.79710584, -2.80863704,  0.67820653, -0.40223669, -2.86818102],
       [ 2.09316131, -1.50697702, -0.60250699,  3.11579357,  3.66117421]])

In [35]:
A@B # same as matmul

array([[-0.84653623,  4.62093752,  2.85473496, -1.46893721,  3.95604992],
       [ 0.38891591,  1.58982333,  0.45926849, -0.17880308,  3.58975524],
       [-2.30293894,  2.57228652, -2.02450367, -3.59212392, -1.18309662],
       [ 0.79710584, -2.80863704,  0.67820653, -0.40223669, -2.86818102],
       [ 2.09316131, -1.50697702, -0.60250699,  3.11579357,  3.66117421]])

In [36]:
x, y = np.ones(5), np.random.rand(5)

In [37]:
x

array([1., 1., 1., 1., 1.])

In [38]:
y

array([0.27140422, 0.54114406, 0.84984498, 0.58234724, 0.92547208])

In [39]:
x.shape

(5,)

In [41]:
xt = x.transpose() # does not transpose for 1-d array
xt

array([1., 1., 1., 1., 1.])

In [42]:
xt.shape

(5,)

In [44]:
x_2d = x.reshape(5,1)
x_2d

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [45]:
x_2d.transpose()

array([[1., 1., 1., 1., 1.]])

In [46]:
x_2d.transpose().shape

(1, 5)

In [48]:
np.dot(2,x) # same as 2*x

array([2., 2., 2., 2., 2.])

In [49]:
2*x

array([2., 2., 2., 2., 2.])

In [50]:
np.matmul(2,x) # multiply by scalar is not allowed

ValueError: matmul: Input operand 0 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)

In [51]:
x

array([1., 1., 1., 1., 1.])

In [52]:
y

array([0.27140422, 0.54114406, 0.84984498, 0.58234724, 0.92547208])

In [54]:
np.dot(x,y) # dot product

3.170212584696836

In [55]:
x.dot(y) # same as np.dot(x,y)

3.170212584696836

In [56]:
np.matmul(x,y) # same as dot product for 1-d array

3.170212584696836

In [57]:
np.matmul(np.reshape(x,(1,5)),np.reshape(y,(1,5))) # dimension mismatch

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 5)

In [58]:
np.matmul(np.reshape(x,(5,1)),np.reshape(y,(1,5))) # matrix multiplication

array([[0.27140422, 0.54114406, 0.84984498, 0.58234724, 0.92547208],
       [0.27140422, 0.54114406, 0.84984498, 0.58234724, 0.92547208],
       [0.27140422, 0.54114406, 0.84984498, 0.58234724, 0.92547208],
       [0.27140422, 0.54114406, 0.84984498, 0.58234724, 0.92547208],
       [0.27140422, 0.54114406, 0.84984498, 0.58234724, 0.92547208]])

In [51]:
x.shape

(5,)

In [52]:
# reshape x into (5,1) 2D array
x_2d = x.reshape(-1,1) # '-1' for the 1st dimension
print(x_2d)
print(x_2d.shape)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]]
(5, 1)


In [53]:
A = np.random.rand(2,2)
A

array([[0.78106028, 0.17855839],
       [0.22292043, 0.47456004]])

In [54]:
A_vec = A.reshape(-1,1)
print(A_vec)
print(A_vec.shape)

[[0.78106028]
 [0.17855839]
 [0.22292043]
 [0.47456004]]
(4, 1)


In [55]:
# convert x_2d back to 1D array
x = x_2d.flatten()
x.shape

(5,)

In [56]:
print(A_vec.flatten())
print(A_vec.flatten().shape)

[0.78106028 0.17855839 0.22292043 0.47456004]
(4,)


In [57]:
A = np.random.randn(5,5)
A

array([[-0.32355688, -1.11712666,  0.93328746,  0.58748195,  1.00390568],
       [-0.73026386,  1.01677884,  0.41408809, -0.59322149,  1.01685924],
       [ 0.32853346,  1.16327995, -1.13316174, -0.51056285,  0.3271277 ],
       [-1.6765983 ,  0.70951181,  1.862031  ,  0.99112721,  0.78884347],
       [-0.26938126,  0.20908154, -0.6997197 , -0.88121479, -0.95636501]])

In [58]:
x

array([1., 1., 1., 1., 1.])

In [59]:
prod = np.dot(A,x)
prod

array([ 1.08399155,  1.12424081,  0.17521651,  2.67491521, -2.59759922])

In [60]:
prod.shape

(5,)

In [61]:
A@x

array([ 1.08399155,  1.12424081,  0.17521651,  2.67491521, -2.59759922])

In [62]:
np.matmul(A,x)

array([ 1.08399155,  1.12424081,  0.17521651,  2.67491521, -2.59759922])

In [63]:
np.dot(A,np.reshape(x,(1,5))) # dimension mismatch

ValueError: shapes (5,5) and (1,5) not aligned: 5 (dim 1) != 1 (dim 0)

In [64]:
np.matmul(A,np.reshape(x,(1,5))) # dimension mismatch

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 5)