# NumPy Operations

## Arithmetic

You can easily perform array with array arithmetic, or scalar with array arithmetic. Let's see some examples:

In [2]:
import numpy as np
arr = np.arange(0,10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr + 1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
2*arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
arr + arr # element-wise addition

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
arr * arr # element-wise product or Hadmard product

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [8]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
# Warning on division by zero, but not an error!
# Just replaced with nan
arr/arr # element-wise division

/Users/Penghang/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [10]:
# Also warning, but not an error instead infinity
1/arr

/Users/Penghang/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [11]:
arr**0.5 # element-wise power

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

## Universal Array Functions

Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

In [12]:
#Taking Square Roots, same as arr**0.5
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [13]:
arr**0.5

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [14]:
#Calcualting exponential (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [15]:
np.max(arr) #same as arr.max()

9

In [16]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [17]:
np.log(arr)

/Users/Penghang/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

## Multiplications

Matrix multiplications: https://docs.scipy.org/doc/numpy/reference/generated/numpy.matmul.html#numpy.matmul

innter product: https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html



In [18]:
A, B = np.random.randn(5,5), np.random.randn(5,5)

In [19]:
A

array([[-0.45239661,  0.27259704, -0.07808012,  0.25628673,  0.16345185],
       [-0.33349286, -2.50945668, -2.62986051,  0.7051743 , -0.11066604],
       [ 0.52696926,  1.04826873,  1.40548076,  0.423349  ,  0.18812455],
       [ 0.68652625,  0.31149716,  0.69993232, -0.19141928,  0.78137807],
       [-0.47278463,  1.2750957 ,  1.94885878,  1.33610551,  1.01921857]])

In [20]:
B

array([[-0.08760227, -2.33780004, -1.91586033, -0.40248651, -3.64704836],
       [ 0.18002674,  0.75314347,  0.09352761,  0.90640498,  0.64636933],
       [-0.38503391,  0.46761371, -0.84284539,  0.15347975, -0.30450144],
       [ 0.70815156, -1.25499267,  0.16266218, -1.20981732, -0.52816264],
       [-0.47031404,  0.75886128,  0.88872424,  0.13432649, -0.51383257]])

In [21]:
B.transpose() # transpose

array([[-0.08760227,  0.18002674, -0.38503391,  0.70815156, -0.47031404],
       [-2.33780004,  0.75314347,  0.46761371, -1.25499267,  0.75886128],
       [-1.91586033,  0.09352761, -0.84284539,  0.16266218,  0.88872424],
       [-0.40248651,  0.90640498,  0.15347975, -1.20981732,  0.13432649],
       [-3.64704836,  0.64636933, -0.30450144, -0.52816264, -0.51383257]])

In [47]:
B.T # transpose

array([[-0.08760227,  0.18002674, -0.38503391,  0.70815156, -0.47031404],
       [-2.33780004,  0.75314347,  0.46761371, -1.25499267,  0.75886128],
       [-1.91586033,  0.09352761, -0.84284539,  0.16266218,  0.88872424],
       [-0.40248651,  0.90640498,  0.15347975, -1.20981732,  0.13432649],
       [-3.64704836,  0.64636933, -0.30450144, -0.52816264, -0.51383257]])

In [22]:
A*B # element-wise product

array([[ 0.03963097, -0.63727737,  0.1495906 , -0.10315195, -0.59611679],
       [-0.06003763, -1.8899809 , -0.24596456,  0.6391735 , -0.07153114],
       [-0.20290103,  0.49018483, -1.18460298,  0.0649755 , -0.05728419],
       [ 0.48616463, -0.39092665,  0.11385252,  0.23158236, -0.4126947 ],
       [ 0.22235725,  0.96762076,  1.73199803,  0.17947437, -0.5237077 ]])

In [23]:
np.dot(A,B) 

array([[ 0.22338537,  1.02880547,  1.14498532,  0.12907892,  1.63053824],
       [ 1.14144898, -3.30906888,  2.63714165, -3.41198545,  0.07944216],
       [-0.18728742, -0.17376939, -1.86010669,  0.46686597, -1.99254616],
       [-0.77660806, -0.20987375, -1.2127966 ,  0.44999258, -2.81597962],
       [-0.012596  ,  2.07356191,  0.50559742,  0.16561736,  0.72563215]])

In [24]:
np.matmul(A,B)

array([[ 0.22338537,  1.02880547,  1.14498532,  0.12907892,  1.63053824],
       [ 1.14144898, -3.30906888,  2.63714165, -3.41198545,  0.07944216],
       [-0.18728742, -0.17376939, -1.86010669,  0.46686597, -1.99254616],
       [-0.77660806, -0.20987375, -1.2127966 ,  0.44999258, -2.81597962],
       [-0.012596  ,  2.07356191,  0.50559742,  0.16561736,  0.72563215]])

In [25]:
A@B # same as matmul

array([[ 0.22338537,  1.02880547,  1.14498532,  0.12907892,  1.63053824],
       [ 1.14144898, -3.30906888,  2.63714165, -3.41198545,  0.07944216],
       [-0.18728742, -0.17376939, -1.86010669,  0.46686597, -1.99254616],
       [-0.77660806, -0.20987375, -1.2127966 ,  0.44999258, -2.81597962],
       [-0.012596  ,  2.07356191,  0.50559742,  0.16561736,  0.72563215]])

In [26]:
x, y = np.ones(5), np.random.rand(5)

In [27]:
x

array([1., 1., 1., 1., 1.])

In [28]:
y

array([0.94866611, 0.37473065, 0.5904764 , 0.0773999 , 0.70055106])

In [29]:
x.shape

(5,)

In [30]:
xt = x.transpose() # does not transpose for 1-d array
xt

array([1., 1., 1., 1., 1.])

In [31]:
xt.shape

(5,)

In [32]:
x_2d = x.reshape(5,1)

In [33]:
x_2d.transpose()

array([[1., 1., 1., 1., 1.]])

In [34]:
x_2d.transpose().shape

(1, 5)

In [35]:
np.dot(2,x) # same as 2*x

array([2., 2., 2., 2., 2.])

In [36]:
2*x

array([2., 2., 2., 2., 2.])

In [37]:
np.matmul(2,x) # multiply by scalar is not allowed

ValueError: matmul: Input operand 0 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)

In [38]:
x

array([1., 1., 1., 1., 1.])

In [39]:
y

array([0.94866611, 0.37473065, 0.5904764 , 0.0773999 , 0.70055106])

In [40]:
np.dot(x,y) # dot product

2.6918241210248643

In [41]:
x.dot(y) # same as np.dot(x,y)

2.6918241210248643

In [42]:
np.matmul(x,y) # same as dot product for 1-d array

2.6918241210248643

In [44]:
np.matmul(np.reshape(x,(1,5)),np.reshape(y,(1,5))) # dimension mismatch

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 5)

In [45]:
np.matmul(np.reshape(x,(5,1)),np.reshape(y,(1,5))) # matrix multiplication

array([[0.94866611, 0.37473065, 0.5904764 , 0.0773999 , 0.70055106],
       [0.94866611, 0.37473065, 0.5904764 , 0.0773999 , 0.70055106],
       [0.94866611, 0.37473065, 0.5904764 , 0.0773999 , 0.70055106],
       [0.94866611, 0.37473065, 0.5904764 , 0.0773999 , 0.70055106],
       [0.94866611, 0.37473065, 0.5904764 , 0.0773999 , 0.70055106]])

In [9]:
x.shape

(5,)

In [14]:
# reshape x into (5,1) 2D array
x_2d = x.reshape(-1,1) # '-1' for the 1st dimension
print(x_2d)
print(x_2d.shape)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]]
(5, 1)


In [15]:
# convert x_2d back to 1D array
x = x_2d.flatten()
x.shape

(5,)

In [85]:
prod = np.dot(A,x)

In [86]:
prod.shape

(5,)

In [89]:
A@x

array([ 0.1004344 , -0.5310956 , -0.45999528, -1.88091985, -3.1253994 ])

In [88]:
np.matmul(A,x)

array([ 0.1004344 , -0.5310956 , -0.45999528, -1.88091985, -3.1253994 ])

In [90]:
np.dot(A,np.reshape(x,(1,5))) # dimension mismatch

ValueError: shapes (5,5) and (1,5) not aligned: 5 (dim 1) != 1 (dim 0)