# NumPy Operations

## Arithmetic

You can easily perform array with array arithmetic, or scalar with array arithmetic. Let's see some examples:

In [1]:
import numpy as np
arr = np.arange(0,10)

In [2]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr + 1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
2*arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [5]:
arr + arr # element-wise addition

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
arr * arr # element-wise product or Hadmard product

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [7]:
arr0 = np.arange(1,5)
arr0

array([1, 2, 3, 4])

In [8]:
arr*arr0

ValueError: operands could not be broadcast together with shapes (10,) (4,) 

In [ ]:
arr - arr

In [ ]:
# Warning on division by zero, but not an error!
# Just replaced with nan
arr/arr # element-wise division

In [9]:
# Also warning, but not an error instead infinity
1/arr

/var/folders/n_/ljlz16dj2wdb9pksfw5ckq_80000gn/T/ipykernel_61026/1360216608.py:2: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [10]:
arr**2 # element-wise power

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [11]:
arr**0.5

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

## Universal Array Functions

Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

In [12]:
#Taking Square Roots, same as arr**0.5
np.sqrt(arr) # same as arr**0.5

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [13]:
arr**0.5

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [14]:
#Calcualting exponential (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [15]:
np.max(arr) #same as arr.max()

np.int64(9)

In [16]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [17]:
np.log(arr)

/var/folders/n_/ljlz16dj2wdb9pksfw5ckq_80000gn/T/ipykernel_61026/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

## Multiplications

Matrix multiplications: https://docs.scipy.org/doc/numpy/reference/generated/numpy.matmul.html#numpy.matmul

inner product: https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html



In [18]:
A, B = np.random.randn(5,5), np.random.randn(5,5)

In [19]:
A

array([[-1.28459657,  1.46894094, -0.3707842 , -0.26316491, -0.92656059],
       [-0.7476587 ,  0.5706269 , -1.05629719, -0.72581709,  0.55036613],
       [-1.06034131, -0.816473  , -0.08994142, -0.16425745,  0.09084819],
       [ 0.63658452,  0.61961524, -2.27561282, -0.55307765, -0.53616016],
       [ 0.18200856,  0.17984457,  0.55357374,  1.93320025,  1.32533238]])

In [20]:
B

array([[ 0.82448632, -1.79330276,  2.38609144,  0.49227977, -1.18515395],
       [-0.6550914 , -0.3800154 ,  1.3562714 , -0.93393737, -1.07360232],
       [-0.11050501,  0.68241789, -0.78376493, -0.59488725,  0.79172943],
       [ 1.91474345, -0.49590678, -0.17341324,  0.73891139,  1.26369163],
       [-2.01262083,  1.59493129,  0.41171604,  0.18173315, -0.4689969 ]])

In [21]:
B.transpose() # transpose

array([[ 0.82448632, -0.6550914 , -0.11050501,  1.91474345, -2.01262083],
       [-1.79330276, -0.3800154 ,  0.68241789, -0.49590678,  1.59493129],
       [ 2.38609144,  1.3562714 , -0.78376493, -0.17341324,  0.41171604],
       [ 0.49227977, -0.93393737, -0.59488725,  0.73891139,  0.18173315],
       [-1.18515395, -1.07360232,  0.79172943,  1.26369163, -0.4689969 ]])

In [22]:
B.T # transpose

array([[ 0.82448632, -0.6550914 , -0.11050501,  1.91474345, -2.01262083],
       [-1.79330276, -0.3800154 ,  0.68241789, -0.49590678,  1.59493129],
       [ 2.38609144,  1.3562714 , -0.78376493, -0.17341324,  0.41171604],
       [ 0.49227977, -0.93393737, -0.59488725,  0.73891139,  0.18173315],
       [-1.18515395, -1.07360232,  0.79172943,  1.26369163, -0.4689969 ]])

In [23]:
A*B # element-wise product

array([[-1.0591323 , -2.63425584, -0.884725  , -0.12955076,  1.09811694],
       [ 0.48978479, -0.21684701, -1.43262568,  0.6778677 , -0.59087436],
       [ 0.11717302, -0.55717579,  0.07049293,  0.09771467,  0.07192718],
       [ 1.21889605, -0.3072714 ,  0.39462138, -0.40867537, -0.6775411 ],
       [-0.36631422,  0.28683973,  0.22791518,  0.35132657, -0.62157678]])

In [24]:
np.dot(A,B) 

array([[-0.6195275 ,  0.1451254 , -1.11811823, -2.14654728, -0.2461797 ],
       [-3.37095288,  1.64082908,  0.17029246, -0.70890406, -1.73816628],
       [-0.82678732,  2.37676068, -3.5010493 ,  0.1891935 ,  1.81184743],
       [ 0.39050252, -3.51083468,  4.01802608,  0.58231546, -3.6688028 ],
       [ 1.00526722,  1.13815544,  0.45475352,  1.26164213,  1.8508831 ]])

In [25]:
C = np.random.rand(4,4)
C

array([[0.87599193, 0.40915617, 0.89444471, 0.16366884],
       [0.1459205 , 0.02582785, 0.98684139, 0.91035744],
       [0.13128794, 0.35970872, 0.32443035, 0.32832012],
       [0.87424764, 0.58071265, 0.56592759, 0.41268716]])

In [26]:
np.dot(A,C)

ValueError: shapes (5,5) and (4,4) not aligned: 5 (dim 1) != 4 (dim 0)

In [27]:
np.matmul(A,B)

array([[-0.6195275 ,  0.1451254 , -1.11811823, -2.14654728, -0.2461797 ],
       [-3.37095288,  1.64082908,  0.17029246, -0.70890406, -1.73816628],
       [-0.82678732,  2.37676068, -3.5010493 ,  0.1891935 ,  1.81184743],
       [ 0.39050252, -3.51083468,  4.01802608,  0.58231546, -3.6688028 ],
       [ 1.00526722,  1.13815544,  0.45475352,  1.26164213,  1.8508831 ]])

In [28]:
np.dot(A,B) 

array([[-0.6195275 ,  0.1451254 , -1.11811823, -2.14654728, -0.2461797 ],
       [-3.37095288,  1.64082908,  0.17029246, -0.70890406, -1.73816628],
       [-0.82678732,  2.37676068, -3.5010493 ,  0.1891935 ,  1.81184743],
       [ 0.39050252, -3.51083468,  4.01802608,  0.58231546, -3.6688028 ],
       [ 1.00526722,  1.13815544,  0.45475352,  1.26164213,  1.8508831 ]])

In [29]:
A@B # same as matmul

array([[-0.6195275 ,  0.1451254 , -1.11811823, -2.14654728, -0.2461797 ],
       [-3.37095288,  1.64082908,  0.17029246, -0.70890406, -1.73816628],
       [-0.82678732,  2.37676068, -3.5010493 ,  0.1891935 ,  1.81184743],
       [ 0.39050252, -3.51083468,  4.01802608,  0.58231546, -3.6688028 ],
       [ 1.00526722,  1.13815544,  0.45475352,  1.26164213,  1.8508831 ]])

In [30]:
x, y = np.ones(5), np.random.rand(5)

In [31]:
x

array([1., 1., 1., 1., 1.])

In [32]:
y

array([0.81763112, 0.83921023, 0.28381391, 0.81394869, 0.37381166])

In [33]:
x.shape

(5,)

In [34]:
xt = x.transpose() # does not transpose for 1-d array
xt

array([1., 1., 1., 1., 1.])

In [35]:
xt.shape

(5,)

In [36]:
x_2d = x.reshape(5,1)
x_2d

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [37]:
x_2d.transpose()

array([[1., 1., 1., 1., 1.]])

In [38]:
x_2d.transpose().shape

(1, 5)

In [39]:
np.dot(2,x) # same as 2*x

array([2., 2., 2., 2., 2.])

In [40]:
2*x

array([2., 2., 2., 2., 2.])

In [41]:
np.matmul(2,x) # multiply by scalar is not allowed

ValueError: matmul: Input operand 0 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)

In [42]:
x

array([1., 1., 1., 1., 1.])

In [43]:
y

array([0.81763112, 0.83921023, 0.28381391, 0.81394869, 0.37381166])

In [44]:
np.dot(x,y) # dot product

np.float64(3.128415594654329)

In [45]:
x.dot(y) # same as np.dot(x,y)

np.float64(3.128415594654329)

In [46]:
np.matmul(x,y) # same as dot product for 1-d array

np.float64(3.128415594654329)

In [47]:
np.matmul(np.reshape(x,(1,5)),np.reshape(y,(1,5))) # dimension mismatch

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 5)

In [48]:
np.matmul(np.reshape(x,(5,1)),np.reshape(y,(1,5))) # matrix multiplication

array([[0.81763112, 0.83921023, 0.28381391, 0.81394869, 0.37381166],
       [0.81763112, 0.83921023, 0.28381391, 0.81394869, 0.37381166],
       [0.81763112, 0.83921023, 0.28381391, 0.81394869, 0.37381166],
       [0.81763112, 0.83921023, 0.28381391, 0.81394869, 0.37381166],
       [0.81763112, 0.83921023, 0.28381391, 0.81394869, 0.37381166]])

In [49]:
x.shape

(5,)

In [50]:
# reshape x into (5,1) 2D array
x_2d = x.reshape(-1,1) # '-1' for the 1st dimension
print(x_2d)
print(x_2d.shape)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]]
(5, 1)


In [51]:
A = np.random.rand(2,2)
A

array([[0.05824721, 0.96578354],
       [0.54995331, 0.96843777]])

In [52]:
A_vec = A.reshape(-1,1)
print(A_vec)
print(A_vec.shape)

[[0.05824721]
 [0.96578354]
 [0.54995331]
 [0.96843777]]
(4, 1)


In [53]:
# convert x_2d back to 1D array
x = x_2d.flatten()
x.shape

(5,)

In [54]:
print(A_vec.flatten())
print(A_vec.flatten().shape)

[0.05824721 0.96578354 0.54995331 0.96843777]
(4,)


In [55]:
A = np.random.randn(5,5)
A

array([[-0.60104635, -0.71719988,  0.30164885, -0.19013217, -0.59016386],
       [-0.06026467,  0.65620813,  1.8938007 , -0.95110445, -0.4392561 ],
       [-0.20947733, -0.85729769,  0.67158018,  1.84762013, -0.51860438],
       [ 0.5599809 , -0.97492452,  0.41704945, -0.17375082, -0.35736447],
       [ 0.84594607, -0.41195677,  0.76724155, -0.19488434,  1.66757455]])

In [56]:
x

array([1., 1., 1., 1., 1.])

In [57]:
prod = np.dot(A,x)
prod

array([-1.79689342,  1.0993836 ,  0.93382091, -0.52900947,  2.67392107])

In [58]:
prod.shape

(5,)

In [59]:
A@x

array([-1.79689342,  1.0993836 ,  0.93382091, -0.52900947,  2.67392107])

In [60]:
np.matmul(A,x)

array([-1.79689342,  1.0993836 ,  0.93382091, -0.52900947,  2.67392107])

In [61]:
np.dot(A,np.reshape(x,(1,5))) # dimension mismatch

ValueError: shapes (5,5) and (1,5) not aligned: 5 (dim 1) != 1 (dim 0)

In [62]:
np.matmul(A,np.reshape(x,(1,5))) # dimension mismatch

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 5)